"""empty message

Revision ID: 864585c5ae96
Revises: 094bbaa5e99f
Create Date: 2023-03-02 20:46:40.002888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864585c5ae96'
down_revision = '094bbaa5e99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fact', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_column('fact')

    # ### end Alembic commands ###
